# Generated by Django 5.0.3 on 2024-04-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burger',
            old_name='details',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='burger',
            old_name='subject',
            new_name='nameOfBurger',
        ),
        migrations.AddField(
            model_name='burger',
            name='haveEaten',
            field=models.BooleanField(default=False),
        ),
    ]
