# Generated by Django 5.0.3 on 2024-04-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('burgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfBurger', models.CharField(max_length=200)),
                ('ingredientOne', models.CharField(max_length=200)),
                ('ingredientTwo', models.CharField(max_length=200)),
                ('ingredientThree', models.CharField(max_length=200)),
                ('ingredientFour', models.CharField(max_length=200)),
                ('ingredientFive', models.CharField(max_length=200)),
                ('ingredientSix', models.CharField(max_length=200)),
                ('ingredientSeven', models.CharField(max_length=200)),
                ('haveEaten', models.BooleanField(default=False)),
            ],
        ),
    ]
